Migrate Build to ESM
cryptomator/hub pull request #291
Opened 2024-08-22 11:07 UTC by overheadhunter

This PR bumps various build-time dependencies and completes the transitions to ESM.

ES modules is the de-facto standard adopted by all major frameworks and tools in recent years. In order to keep our dependencies up to date, we had to migrate them sooner or later.

* `vite.js` has been spitting out [deprecation warnings](https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated) for some time already
* `chai` [version 5 dropped support for other module systems](https://github.com/chaijs/chai/releases/tag/v5.0.0)
* `eslint` is [urging users to adopt the _Flat Configuration Format_](https://eslint.org/blog/2023/10/flat-config-rollout-plans/) with plans to drop the older `.eslintrc.js` format, which is incompatible with ESM

This PR also adjusts VSCode settings for it to pick up the new linter and test configurations.

Last but not least, plenty of linter warnings/errors have been fixed, as it seems like the linter has not been run recently.

2024-08-22 13:45 UTC, overheadhunter commented on frontend/src/common/util.ts
> +  function debounceCore(this: unknown, ...args: unknown[]) {
not planned to change this

2024-08-22 20:23 UTC, SailReal requested changes
Looks good to me but `npm outdated` shows still some outdated packages (Keycloak is fixed on the dev branch, so this can be skipped), is there a reason for it?

```
Package                        Current   Latest  Location                                   Depended by
@rollup/rollup-linux-x64-gnu    4.20.0   4.21.0  node_modules/@rollup/rollup-linux-x64-gnu  frontend
@types/node                    20.14.15  22.5.0  node_modules/@types/node                   frontend
keycloak-js                     25.0.2   25.0.4  node_modules/keycloak-js                   frontend
vite                             5.4.0    5.4.2  node_modules/vite                          frontend
vue-i18n                        9.13.1   9.14.0  node_modules/vue-i18n                      frontend
```

2024-08-23 06:21 UTC, overheadhunter commented
> Looks good to me but `npm outdated` shows still some outdated packages (Keycloak is fixed on the dev branch, so this can be skipped), is there a reason for it?

Except for node (which I didn't update because I didn't want to touch GitHub Actions as well) the reason simply is that they all outpaced this PR.

2024-08-23 07:19 UTC, SailReal approved these changes

2024-08-23 09:26 UTC, merged